//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpConcepts.Concepts.DatabaseInteraction.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GameHubEntities : DbContext
    {
        public GameHubEntities()
            : base("name=GameHubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BATTLEHISTORY> BATTLEHISTORies { get; set; }
        public virtual DbSet<GAME> GAMES { get; set; }
        public virtual DbSet<PLAYER> PLAYERS { get; set; }
    
        public virtual ObjectResult<GETNAMEHAVINGCHARACTER_Result> GETNAMEHAVINGCHARACTER(string @char)
        {
            var charParameter = @char != null ?
                new ObjectParameter("char", @char) :
                new ObjectParameter("char", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETNAMEHAVINGCHARACTER_Result>("GETNAMEHAVINGCHARACTER", charParameter);
        }
    }
}
